countries = {0: {'name': 'Unknown', 'short_name': 'UKN'}, 31: {'name': 'CONCACAF', 'short_name': 'CNCF'},
             32: {'name': 'CONMEBOL', 'short_name': 'CON'}, 34: {'name': 'CAF', 'short_name': 'CAF'},
             35: {'name': 'OFC', 'short_name': 'OFC'}, 36: {'name': 'UEFA', 'short_name': 'UEFA'},
             37: {'name': 'Albania', 'short_name': 'ALB'}, 38: {'name': 'Austria', 'short_name': 'AUT'},
             39: {'name': 'Belgium', 'short_name': 'BEL'}, 40: {'name': 'Croatia', 'short_name': 'CRO'},
             41: {'name': 'Denmark', 'short_name': 'DEN'}, 42: {'name': 'Macedonia FYR', 'short_name': 'MKD'},
             43: {'name': 'France', 'short_name': 'FRA'}, 44: {'name': 'Greece', 'short_name': 'GRE'},
             45: {'name': 'Ireland', 'short_name': 'IRE'}, 46: {'name': 'Kazakhstan', 'short_name': 'KAZ'},
             47: {'name': 'Lithuania', 'short_name': 'LIT'}, 48: {'name': 'Moldova', 'short_name': 'MOL'},
             49: {'name': 'Norway', 'short_name': 'NOR'}, 50: {'name': 'Romania', 'short_name': 'ROM'},
             51: {'name': 'Scotland', 'short_name': 'SCO'}, 52: {'name': 'Slovenia', 'short_name': 'SLO'},
             53: {'name': 'Switzerland', 'short_name': 'SUI'}, 54: {'name': 'Wales', 'short_name': 'WAL'},
             55: {'name': 'Andorra', 'short_name': 'AND'}, 56: {'name': 'Azerbaijan', 'short_name': 'AZE'},
             57: {'name': 'Bosnia', 'short_name': 'BOS'}, 58: {'name': 'Cyprus', 'short_name': 'CYP'},
             59: {'name': 'England', 'short_name': 'ENG'}, 60: {'name': 'Faroe Islands', 'short_name': 'FAR'},
             61: {'name': 'Georgia', 'short_name': 'GEO'}, 62: {'name': 'Hungary', 'short_name': 'HUN'},
             63: {'name': 'Israel', 'short_name': 'ISR'}, 64: {'name': 'Latvia', 'short_name': 'LAT'},
             65: {'name': 'Luxemburg', 'short_name': 'LUX'}, 66: {'name': 'Holland', 'short_name': 'HOL'},
             67: {'name': 'Poland', 'short_name': 'POL'}, 68: {'name': 'Russia', 'short_name': 'RUS'},
             69: {'name': 'Serbia', 'short_name': 'SRB'}, 70: {'name': 'Spain', 'short_name': 'SPA'},
             71: {'name': 'Turkey', 'short_name': 'TUR'}, 72: {'name': 'Armenia', 'short_name': 'ARM'},
             73: {'name': 'Belarus', 'short_name': 'BLR'}, 74: {'name': 'Bulgaria', 'short_name': 'BUL'},
             75: {'name': 'Czech Rep.', 'short_name': 'CZE'}, 76: {'name': 'Estonia', 'short_name': 'EST'},
             77: {'name': 'Finland', 'short_name': 'FIN'}, 78: {'name': 'Germany', 'short_name': 'GER'},
             79: {'name': 'Iceland', 'short_name': 'ICE'}, 80: {'name': 'Italy', 'short_name': 'ITA'},
             81: {'name': 'Liechtenstein', 'short_name': 'LIE'}, 82: {'name': 'Malta', 'short_name': 'MAL'},
             83: {'name': 'N. Ireland', 'short_name': 'NIR'}, 84: {'name': 'Portugal', 'short_name': 'POR'},
             85: {'name': 'San Marino', 'short_name': 'SMR'}, 86: {'name': 'Slovakia', 'short_name': 'SVK'},
             87: {'name': 'Sweden', 'short_name': 'SWE'}, 88: {'name': 'Ukraine', 'short_name': 'UKR'},
             89: {'name': 'Argentina', 'short_name': 'ARG'}, 90: {'name': 'Bolivia', 'short_name': 'BOL'},
             91: {'name': 'Brazil', 'short_name': 'BRA'}, 92: {'name': 'Chile', 'short_name': 'CHI'},
             93: {'name': 'Colombia', 'short_name': 'COL'}, 94: {'name': 'Ecuador', 'short_name': 'ECU'},
             95: {'name': 'Paraguay', 'short_name': 'PAR'}, 96: {'name': 'Peru', 'short_name': 'PER'},
             97: {'name': 'Uruguay', 'short_name': 'URU'}, 98: {'name': 'Venezuela', 'short_name': 'VEN'},
             99: {'name': 'American Samoa', 'short_name': 'ASA'}, 100: {'name': 'Fiji', 'short_name': 'FIJ'},
             101: {'name': 'Samoa', 'short_name': 'SAM'}, 102: {'name': 'Tonga', 'short_name': 'TGA'},
             103: {'name': 'Australia', 'short_name': 'AUS'}, 104: {'name': 'New Zealand', 'short_name': 'NZL'},
             105: {'name': 'Solomon Islands', 'short_name': 'SOL'}, 106: {'name': 'Vanuatu', 'short_name': 'VAN'},
             107: {'name': 'Cook Islands', 'short_name': 'COK'}, 108: {'name': 'Papua New Guinea', 'short_name': 'PNG'},
             109: {'name': 'Tahiti', 'short_name': 'TAH'}, 110: {'name': 'Afghanistan', 'short_name': 'AFG'},
             111: {'name': 'Bhutan', 'short_name': None}, 112: {'name': 'China', 'short_name': 'CHN'},
             113: {'name': 'Hong Kong', 'short_name': 'HKG'}, 114: {'name': 'Iran', 'short_name': 'IRN'},
             115: {'name': 'Jordan', 'short_name': 'JOR'}, 116: {'name': 'Kuwait', 'short_name': 'KUW'},
             117: {'name': 'Lebanon', 'short_name': 'LBN'}, 118: {'name': 'Maldives', 'short_name': 'MDV'},
             119: {'name': 'Nepal', 'short_name': 'NEP'}, 120: {'name': 'Palestine', 'short_name': 'PAL'},
             121: {'name': 'Saudi Arabia', 'short_name': 'KSA'}, 122: {'name': 'Syria', 'short_name': 'SYR'},
             123: {'name': 'Turkmenistan', 'short_name': 'TKM'}, 124: {'name': 'Vietnam', 'short_name': 'VIE'},
             125: {'name': 'Bahrain', 'short_name': 'BHR'}, 126: {'name': 'Brunei', 'short_name': 'BRU'},
             127: {'name': 'Taipei', 'short_name': 'TPE'}, 128: {'name': 'India', 'short_name': 'IND'},
             129: {'name': 'Iraq', 'short_name': 'IRQ'}, 130: {'name': 'North Korea', 'short_name': 'PRK'},
             131: {'name': 'Kyrgyzstan', 'short_name': 'KGZ'}, 132: {'name': 'Macau', 'short_name': 'MAC'},
             133: {'name': 'Mongolia', 'short_name': 'MGL'}, 134: {'name': 'Oman', 'short_name': 'OMA'},
             135: {'name': 'Philippines', 'short_name': 'PHI'}, 136: {'name': 'Singapore', 'short_name': 'SIN'},
             137: {'name': 'Tajikistan', 'short_name': 'TJK'}, 138: {'name': 'UAE', 'short_name': 'UAE'},
             139: {'name': 'Yemen', 'short_name': 'YEM'}, 140: {'name': 'Bangladesh', 'short_name': 'BAN'},
             141: {'name': 'Cambodia', 'short_name': 'CAM'}, 142: {'name': 'Guam', 'short_name': 'GUM'},
             143: {'name': 'Indonesia', 'short_name': 'IDN'}, 144: {'name': 'Japan', 'short_name': 'JPN'},
             145: {'name': 'South Korea', 'short_name': 'KOR'}, 146: {'name': 'Laos', 'short_name': 'LAO'},
             147: {'name': 'Malaysia', 'short_name': 'MAS'}, 148: {'name': 'Myanmar', 'short_name': 'MYA'},
             149: {'name': 'Pakistan', 'short_name': 'PAK'}, 150: {'name': 'Qatar', 'short_name': 'QAT'},
             151: {'name': 'Sri Lanka', 'short_name': 'SRI'}, 152: {'name': 'Thailand', 'short_name': 'THA'},
             153: {'name': 'Uzbekistan', 'short_name': 'UZB'}, 154: {'name': 'Algeria', 'short_name': 'ALG'},
             155: {'name': 'Botswana', 'short_name': 'BOT'}, 156: {'name': 'Cameroon', 'short_name': 'CMR'},
             157: {'name': 'Chad', 'short_name': 'CHA'}, 158: {'name': 'DR Congo', 'short_name': 'DRC'},
             159: {'name': 'Equatorial Guinea', 'short_name': 'EQG'}, 160: {'name': 'Gabon', 'short_name': 'GAB'},
             161: {'name': 'Guinea', 'short_name': 'GUI'}, 162: {'name': 'Lesotho', 'short_name': 'LES'},
             163: {'name': 'Madagascar', 'short_name': 'MAD'}, 164: {'name': 'Mauritania', 'short_name': 'MTN'},
             165: {'name': 'Mozambique', 'short_name': 'MOZ'}, 166: {'name': 'Nigeria', 'short_name': 'NGA'},
             167: {'name': 'Senegal', 'short_name': 'SEN'}, 168: {'name': 'Somalia', 'short_name': 'SOM'},
             169: {'name': 'Swaziland', 'short_name': 'SWZ'}, 170: {'name': 'Tunisia', 'short_name': 'TUN'},
             171: {'name': 'Zimbabwe', 'short_name': 'ZIM'}, 172: {'name': 'Angola', 'short_name': 'ANG'},
             173: {'name': 'Burkina Faso', 'short_name': 'BFA'}, 174: {'name': 'Cape Verde', 'short_name': None},
             175: {'name': 'Congo', 'short_name': 'CGO'}, 177: {'name': 'Eritrea', 'short_name': None},
             178: {'name': 'Gambia', 'short_name': 'GAM'}, 179: {'name': 'Guinea-Bissau', 'short_name': 'GNB'},
             180: {'name': 'Liberia', 'short_name': 'LBR'}, 181: {'name': 'Malawi', 'short_name': 'MWI'},
             182: {'name': 'Mauritius', 'short_name': 'MRI'}, 183: {'name': 'Namibia', 'short_name': 'NAM'},
             184: {'name': 'Rwanda', 'short_name': 'RWA'}, 185: {'name': 'Seychelles', 'short_name': 'SEY'},
             186: {'name': 'South Africa', 'short_name': 'RSA'}, 187: {'name': 'Tanzania', 'short_name': 'TAN'},
             188: {'name': 'Uganda', 'short_name': 'UGA'}, 189: {'name': 'Benin', 'short_name': 'BEN'},
             190: {'name': 'Burundi', 'short_name': 'BDI'}, 191: {'name': 'Central African Rep.', 'short_name': 'CTA'},
             192: {'name': 'Egypt', 'short_name': 'EGY'}, 193: {'name': 'Ethiopia', 'short_name': 'ETH'},
             194: {'name': 'Ghana', 'short_name': 'GHA'}, 195: {'name': 'Kenya', 'short_name': 'KEN'},
             196: {'name': 'Libya', 'short_name': 'LBY'}, 197: {'name': 'Mali', 'short_name': 'MLI'},
             198: {'name': 'Morocco', 'short_name': 'MAR'}, 199: {'name': 'Niger', 'short_name': 'NIG'},
             200: {'name': 'Sao Tome and Principe', 'short_name': 'STP'},
             201: {'name': 'Sierra Leone', 'short_name': 'SLE'}, 202: {'name': 'Sudan', 'short_name': 'SUD'},
             203: {'name': 'Togo', 'short_name': 'TOG'}, 204: {'name': 'Zambia', 'short_name': 'ZAM'},
             205: {'name': 'Anguilla', 'short_name': None}, 206: {'name': 'Bahamas', 'short_name': 'BAH'},
             207: {'name': 'Bermuda', 'short_name': 'BER'}, 208: {'name': 'Cayman Islands', 'short_name': 'CAY'},
             209: {'name': 'Dominica', 'short_name': None}, 210: {'name': 'Grenada', 'short_name': None},
             211: {'name': 'Haiti', 'short_name': 'HAI'}, 212: {'name': 'Mexico', 'short_name': 'MEX'},
             213: {'name': 'Nicaragua', 'short_name': 'NCA'}, 214: {'name': 'Saint Lucia', 'short_name': None},
             215: {'name': 'Surinam', 'short_name': 'SUR'}, 216: {'name': 'US Virgin Islands', 'short_name': 'VIR'},
             217: {'name': 'Antigua & Barbuda', 'short_name': 'ATB'}, 218: {'name': 'Barbados', 'short_name': None},
             219: {'name': 'British Virgin Island', 'short_name': None},
             220: {'name': 'Costa Rica', 'short_name': 'CRC'},
             221: {'name': 'Dominican Rep.', 'short_name': 'DOM'}, 222: {'name': 'Guatemala', 'short_name': 'GUA'},
             223: {'name': 'Honduras', 'short_name': 'HON'}, 224: {'name': 'Montserrat', 'short_name': 'MSR'},
             225: {'name': 'Panama', 'short_name': 'PAN'}, 226: {'name': 'St Kitts & Nevis', 'short_name': None},
             227: {'name': 'Trinidad & Tobago', 'short_name': 'TRI'},
             228: {'name': 'United States', 'short_name': 'USA'},
             229: {'name': 'Aruba', 'short_name': None}, 230: {'name': 'Belize', 'short_name': 'BLZ'},
             231: {'name': 'Canada', 'short_name': 'CAN'}, 232: {'name': 'Cuba', 'short_name': None},
             233: {'name': 'El Salvador', 'short_name': 'SLV'}, 234: {'name': 'Guyana', 'short_name': 'GUY'},
             235: {'name': 'Jamaica', 'short_name': 'JAM'}, 236: {'name': 'Netherlands Antilles', 'short_name': None},
             237: {'name': 'Puerto Rico', 'short_name': 'PUR'},
             238: {'name': 'St Vincent/Grenadine', 'short_name': 'VIN'},
             239: {'name': 'Turks & Caicos Islands', 'short_name': None},
             247: {'name': 'International', 'short_name': 'INT'}, 248: {'name': 'FIFA', 'short_name': 'FIFA'},
             249: {'name': 'AFC', 'short_name': 'AFC'}, 250: {'name': 'Scandinavia', 'short_name': 'SCA'},
             254: {'name': 'Ivory Coast', 'short_name': 'IVC'}, 281: {'name': 'Djibouti', 'short_name': 'DJB'},
             282: {'name': 'Montenegro', 'short_name': 'MNE'}, 283: {'name': 'Comoros', 'short_name': 'CMO'},
             284: {'name': 'Arab', 'short_name': 'Arab'}, 285: {'name': 'Bhutan', 'short_name': 'BHU'},
             286: {'name': 'Timor-Leste', 'short_name': None}, 287: {'name': 'Zanzibar', 'short_name': 'ZBR'},
             288: {'name': 'Réunion', 'short_name': 'RUN'}, 290: {'name': 'New Caledonia', 'short_name': 'NCL'},
             291: {'name': 'Benelux', 'short_name': 'BENL'}, 292: {'name': 'Gibraltar', 'short_name': 'GIB'},
             293: {'name': 'Kosovo', 'short_name': 'KOS'}, 294: {'name': 'South Sudan', 'short_name': 'SSD'},
             295: {'name': 'Guadeloupe', 'short_name': 'GDL'}, 296: {'name': 'Sint Maarten', 'short_name': 'SMN'},
             300: {'name': 'New Caledonia', 'short_name': 'CLD'}, 301: {'name': 'Taiwan', 'short_name': None}}
